### ISSUE TITLE
Will ArmorLab support non-Nvidia GPUs?

### ISSUE THREAD

**Issue by unfa** [armory3d/armorlab#1]
Usually AI-based software depends on CUDA for operation, which limits the user base to people who have Nvidia GPUs.

Are there plans to support other GPU vendors as well?

**Comment by Calinou** [comment]
I see no mention of `cuda` in ArmorLab's codebase.

**Comment by luboslenco** [comment]
It's using the https://onnxruntime.ai/ as of now. Will make sure to pick the appropriate gpu backends that support other gpu vendors as well.

**Comment by unfa** [comment]
Thanks!
