### ISSUE TITLE
inpaint doesn't do anything

### ISSUE THREAD

**Issue by SlincHD** [armory3d/armorlab#15]
lates githup relise
![image](https://user-images.githubusercontent.com/85231739/193101924-e094f52c-70bf-43c8-9cdb-36526d4864d6.png)
it just sits there doing nothing
idk it dosn't freez but it also dosn't do anything
![image](https://user-images.githubusercontent.com/85231739/193102084-d3c1cc5e-ded7-499e-a872-58298ef06d50.png)

**Comment by SlincHD** [comment]
forgot to say that it only happends when i use inpaint, tyling node

**Comment by SlincHD** [comment]
forgot to say that it only happends when i use inpaint, tyling node

**Comment by luboslenco** [comment]
Fixed in latest builds, thanks for report.

**Comment by SlincHD** [comment]
Is it on gumroad?
