### ISSUE TITLE
PBR extractor dosn't work

### ISSUE THREAD

**Issue by SlincHD** [armory3d/armorlab#16]
using one of the sample images you can see that the pbr extractor dose nothing after completing it's run
![image](https://user-images.githubusercontent.com/85231739/193361625-39621b21-6eb9-4476-9662-b72fdaaebc8f.png)
ArmorLab.org - v0.1 (2022-09-29) - dcc6500
Windows - Direct3D11
NVIDIA GeForce RTX 3060

**Comment by SlincHD** [comment]
i sadly don't have the skils to do that i just used the lates githup relise

**Comment by SlincHD** [comment]
btw where do we see when the githup version is getting updated?

**Comment by SlincHD** [comment]
ok after reinsatlling it it just fixed itself but https://github.com/armory3d/armorlab/issues/15#issue-1391236706 this still dosn't work

**Comment by luboslenco** [comment]
Will continue at https://github.com/armory3d/armorlab/issues/15.
