### ISSUE TITLE
Errors when building the .sln    

### ISSUE THREAD

**Issue by SimonBreithofer** [armory3d/armorlab#18]
In the Windows Installation Process i'm stuck here: _# Build and run for x64 & release_

When building the solution i get a few errors in the armorlab\Libraries\plugins\Sources\plugins.cpp File and don't end up with an ArmorLab.exe. 
Seems to me like some missing definitions for the ArrayBuffer::Contents stuff coming from the v8 namespace. Would love some guidance. 
 
![Capture](https://user-images.githubusercontent.com/56673775/201339459-bb25d0d6-e75a-4ae8-b318-9eea240b7f03.PNG)

ArmorLab.org - v0.1
Windows - Direct3D11
NVIDIA GeForce RTX 3090

**Comment by shiena** [comment]
Probably need to migrate to the New ArrayBuffer API
https://docs.google.com/document/d/1sTc_jRL87Fu175Holm5SV0kajkseGl2r8ifGY76G35k/

**Comment by luboslenco** [comment]
Pushed a fix, thanks for report.

**Comment by SimonBreithofer** [comment]
thanks a lot, 
will try it out as soon as i can.
