### ISSUE TITLE
ArmorLab Not Responding when hitting run button

### ISSUE THREAD

**Issue by N0tACyb0rg** [armory3d/armorlab#2]
**ArmorLab version:**
545b2ad024d9dbced2a4ce2287d54cfd8d75159f
**OS/device including version:**

Ryzen 3 3100
16 GB RAM
MSI GeForce RTX 2080 Super
GeForce Game-Ready driver 471.68

**Issue description:**

I loaded a picture I quickly took to test (it was stable), and setup the image for tiling, then hooked it up and hit run. ArmorLab proceeded to have a status of *Not Responding* for about 5 minutes until I used Alt+F4 to close the program. My PC did kick up quite a bit during the process.
**Steps to reproduce:**

Image of the interface:
![image](https://user-images.githubusercontent.com/47341194/131205512-81863019-8ff0-4ab4-aa65-c4e5fad9ff63.png)
Picture used (for reference):
![image](https://user-images.githubusercontent.com/47341194/131205571-cf362b32-fdd3-46af-919d-177eba409694.png)
Node Setup:
![image](https://user-images.githubusercontent.com/47341194/131205557-1e4c3221-9af2-4cbc-b64b-eb0489ee076c.png)
Not responding screen after hitting run & image of Task Manager:
![image](https://user-images.githubusercontent.com/47341194/131205594-78bbffb0-1b39-480e-9dd6-af13cfcfa537.png)
![image](https://user-images.githubusercontent.com/47341194/131205605-73c3a6e6-5d9d-4cc2-832e-e4224b5e7cbd.png)
Welp, that's all I got.

**Comment by luboslenco** [comment]
Sorry not ready yet, will provide a readme when done.
