### ISSUE TITLE
Error LNK1181 and 2001 when compiling 

### ISSUE THREAD

**Issue by BigBallerBenzie** [armory3d/armorlab#24]
When attempting to compile I get these errors: 
![image](https://user-images.githubusercontent.com/58898437/205526072-103ea1b7-5045-441a-ab9f-bb91499f14da.png)

Attempted to fix by adding/models to the path. After I get this error: 
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'C:\Users\jacob\Documents\armorlab\Assets\models.obj'	ArmorLab	C:\Users\jacob\Documents\armorlab\build\LINK	1	
```
Seeming to be missing models.obj which I can not find reference to anywhere

**Comment by luboslenco** [comment]
Updating to the latest Visual Studio version should resolve this. https://github.com/actions/runner-images/issues/6091
