### ISSUE TITLE
Compiled like Armorypaint but it crashes when I click run button

### ISSUE THREAD

**Issue by musuvataf** [armory3d/armorlab#3]
Hello, I compiled armorlab project like armorypaint and copied armorcore/build/x64/release folder content to armorlab/build/krom. Yes armorlab.exe works. I can add a texture and can save the project. I added Image texture node and connected to photo to pbr node. When I click run button, program crashes after a while. Can you help me about how it works?

Thanks in advance

![Screenshot_1](https://user-images.githubusercontent.com/72340783/133947935-6474d367-c276-49be-b41e-c4f5360bcb96.jpg)

Texture file :
![texture](https://user-images.githubusercontent.com/72340783/133947942-6705f67b-72c4-470b-a2d3-8e52b6dcc927.jpg)

**Comment by luboslenco** [comment]
Hello, see https://github.com/armory3d/armorlab/issues/2.

**Comment by musuvataf** [comment]
ok. thank you, I will try to write my own AI-powered photo to pbr tool. First I will have Tensorflow detected/extracted fractions/textures and then materialize the extraction. If your tool worked, I wouldn't write my own
