### ISSUE TITLE
Tiling algoruthm is broken kinda

### ISSUE THREAD

**Issue by SlincHD** [armory3d/armorlab#6]
![image](https://user-images.githubusercontent.com/85231739/179061946-5c599162-8626-4709-83af-062e2b766b6a.png)
this is what the tiling node dose to the brick texture and idk if it is a bug or somthing but i wanted to make you aware of it

**Comment by luboslenco** [comment]
You can try to disable the `auto` option and use the new stable diffusion tilling as pictured below. Requires latest builds updated today! There is some quality loss and you may have to try several times before getting satisfying result, but will improve that over time. Will post more tiling fixes at https://github.com/armory3d/armortools/issues/1513.

![a](https://user-images.githubusercontent.com/3685704/194549273-6a169185-2079-441d-bdd0-d6c8368415e5.jpg)

**Comment by SlincHD** [comment]
that is super interesting will look in to it!
