### ISSUE TITLE
Crash app

### ISSUE THREAD

**Issue by Axelaredz** [armory3d/armorlab#7]
Crash app on push run button
Videocard 850M
![image](https://user-images.githubusercontent.com/1193738/179265950-c68f4192-43d8-472f-98d1-494e708180ab.png)
![image](https://user-images.githubusercontent.com/1193738/179266385-9d3678ea-72d6-48a9-9b2c-d863dbcf21fb.png)
![image](https://user-images.githubusercontent.com/1193738/179342429-ae111a01-874b-4f43-b70d-cf491cb7ca3a.png)

DXR version not running

**Comment by luboslenco** [comment]
Investigating at https://github.com/armory3d/armortools/issues/1502, thanks for report. Will also post a fix at https://github.com/armory3d/armortools/issues/1502.
